# Generated by Django 3.0.8 on 2020-08-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('makeweb', models.CharField(blank=True, max_length=300, null=True)),
                ('solution', models.CharField(blank=True, max_length=300, null=True)),
                ('gain', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
