# Generated by Django 3.0.8 on 2020-08-04 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apply', '0005_auto_20200804_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyinformation',
            name='class_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_code_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applyinformation',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applyinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
