# Generated by Django 3.0.8 on 2020-08-04 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apply', '0006_auto_20200804_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyinformation',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='applyinformation',
            name='major',
        ),
        migrations.AlterField(
            model_name='applyinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
