# Generated by Django 3.0.8 on 2020-08-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        
        ('question', '0002_auto_20200817_1419'),
    ]

    operations = [
    ]
