# Generated by Django 3.0.8 on 2020-08-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_manager_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager_ok',
        ),
    ]
