# Generated by Django 3.0.8 on 2020-08-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200817_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='question',
            new_name='title',
        ),
    ]
