# Generated by Django 3.0.8 on 2020-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200817_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
