# Generated by Django 3.0.8 on 2020-08-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_merge_20200817_1942'),
        ('manager', '0005_auto_20200817_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
            preserve_default=False,
        ),
    ]
