# Generated by Django 3.0.8 on 2020-08-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_manager_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='title',
        ),
    ]
